version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: db
    restart: always
    ports:
      - 17017:27017
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=direct-contact